name: Deploy ERC-4337 staging bundler

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ORGANIZATION: happychaindevs
  PM2_PROCESS_NAME: happy-staging-bundler
  PORT: 49533
  RPC_URL: https://happy-testnet-sepolia.rpc.caldera.xyz/http
  STAGING_BUNDLER_URL: https://bundler-staging.happy.tech

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      
      - name: Show wallets address and balances
        run: |
          EXECUTOR_WALLETS='${{ secrets.STAGING_BUNDLER_EXECUTOR_WALLETS }}'
          echo "===== Executor wallet(s) ====="
          if [[ -n "$EXECUTOR_WALLETS" ]]; then
            # Remove spaces and extra double quotes
            EXECUTOR_WALLETS=$(echo "$EXECUTOR_WALLETS" | tr -d '[:space:]' | tr -d '"')
            IFS=',' read -ra ADDR <<< "$EXECUTOR_WALLETS"
      
            for WALLET in "${ADDR[@]}"; do
              WALLET_ADDRESS=$(cast wallet address "$WALLET")
              WALLET_BALANCE=$(cast balance "$WALLET_ADDRESS" --rpc-url ${{ env.RPC_URL }} --ether)
              echo "Executor wallet: $WALLET_ADDRESS with balance: $WALLET_BALANCE"
            done
          else
            echo "No executor wallets found!"
          fi
          UTILITY_WALLET='${{ secrets.STAGING_BUNDLER_UTILITY_WALLET }}'
          UTILITY_WALLET=$(echo "$UTILITY_WALLET" | tr -d '[:space:]' | tr -d '"') # Remove spaces and extra double quotes
          UTILITY_WALLET_ADDRESS=$(cast wallet address "$UTILITY_WALLET")
          UTILITY_WALLET_BALANCE=$(cast balance "$UTILITY_WALLET_ADDRESS" --rpc-url ${{ env.RPC_URL }} --ether)
          echo "Utility wallet: $UTILITY_WALLET_ADDRESS, balance $UTILITY_WALLET_BALANCE"

      - name: Print Bundler Config
        run: |
          cat packages/bundler/configs/config.happySepolia.json
        
      - name: Build code
        run: |
          cd packages/bundler
          make setup

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "packages/bundler/alto/*,packages/bundler/configs/config.happySepolia.json"
          target: /home/deployer/happy-staging-bundler
          strip_components: 2   
          rm: true

      - name: Deploy bundler to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod -R o+rX /home/deployer/happy-staging-bundler
            mv /home/deployer/happy-staging-bundler /tmp
            sudo -u staging_bundler bash -c '
              rm -rf /home/staging_bundler/happy-staging-bundler
              cp -r /tmp/happy-staging-bundler /home/staging_bundler/happy-staging-bundler
              cd /home/staging_bundler/happy-staging-bundler
              pm2 delete ${{ env.PM2_PROCESS_NAME }}
              pm2 start ./alto/src/lib/cli/alto.js \
                  --name ${{ env.PM2_PROCESS_NAME }} \
                  -- run \
                  --config ./configs/config.happySepolia.json \
                  --executor-private-keys ${{ secrets.STAGING_BUNDLER_EXECUTOR_WALLETS }} \
                  --utility-private-key ${{ secrets.STAGING_BUNDLER_UTILITY_WALLET }} \
                  --port ${{ env.PORT }}
              pm2 save
            '
            rm -rf /tmp/happy-staging-bundler
      
      - name: Send chainId request (healthcheck)
        run: |
          sleep 10 # wait for the server to start
          curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' ${{ env.STAGING_BUNDLER_URL }} --fail